### ISSUE TITLE
kvstore-perf core mask.

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#35]
Currently the tool only supports N number of cores, counting from core 0.  We need to be able to support a range of specific cores.  They should be of the format..

1,2,3,6-10,12-40

**Comment by dwaddington** [comment]
I see a single range is supported, but no multiple?

**Comment by tjanssen3** [comment]
Done on commit ID 0fe872f3d04548718e5825f2dcdf8db7d71e2b04. Pasting in comments about this change below:

```
kvstore-perf: core mask supports ranges, singles

    general:
    - behavior of the --cores input argument has changed (see issue #35)
    - previously, --cores=N would run tasks on cores 0 to N-1
    - now, cores input arg supports arbitrary masks made up of single cores
      (separated by commas) and ranges (separated by '-' character)
    - example: --cores="1,2,3,6-10,12-40" will run tasks on cores 1, 2, 3, 6 to 10, and 12-40
    - example: --cores="8" will run tasks on core 8
```
